import { initialData } from "./data.js";
import { prioritizedTasks, safeText } from "./logic.js";

const STORAGE_KEY = "humble-african-command-centre-v2";
const clone = v => JSON.parse(JSON.stringify(v));
let data = load();
let page = location.hash.slice(1) || "overview";
const main = document.querySelector("main");

const pages = [
  ["FOCUS", [["overview","⌂","Overview"],["today","☀","Do This Next"],["tasks","✓","Action Board"]]],
  ["BUSINESS", [["products","▦","Products"],["marketplaces","◎","Sales Channels"],["kdp","K","Amazon KDP"]]],
  ["GROWTH", [["marketing","◉","Marketing"],["timeline","◷","Milestones"],["decisions","□","Operating Rules"]]]
];
const titles = Object.fromEntries(pages.flatMap(g=>g[1]).map(x=>[x[0],x[2]]));
function load(){try{return {...clone(initialData),...JSON.parse(localStorage.getItem(STORAGE_KEY)||"{}")}}catch{return clone(initialData)}}
function save(msg="Saved"){localStorage.setItem(STORAGE_KEY,JSON.stringify(data));toast(msg)}
function toast(msg){const el=document.querySelector("#toast");el.textContent=msg;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),1600)}
function cls(s){return String(s).toLowerCase().replaceAll(" ","-")}
function pill(s){return `<span class="pill ${cls(s)}">${safeText(s)}</span>`}
function intro(title,copy){return `<div class="page-intro"><div class="section-head"><div><h2>${title}</h2><p>${copy}</p></div></div></div>`}
function footer(){return `<footer><strong>HUMBLE AFRICAN</strong> · Rooted in Africa. Made for everyone.<br><small>Keep passwords, bank details, identity documents and private source files out of this public dashboard.</small></footer>`}
function renderNav(){document.querySelector("#navigation").innerHTML=pages.map(([label,items])=>`<div class="nav-group"><div class="nav-label">${label}</div>${items.map(([id,icon,name])=>`<button class="nav-button ${page===id?"active":""}" data-page="${id}"><span class="nav-icon">${icon}</span>${name}</button>`).join("")}</div>`).join("")}

function renderOverview(){
 const next=prioritizedTasks(data.tasks)[0];
 const live=data.marketplaces.filter(x=>x.status==="LIVE").length;
 const blocked=data.tasks.filter(x=>x.status==="BLOCKED").length;
 const active=data.tasks.filter(x=>x.status==="IN PROGRESS").length;
 main.innerHTML=`<section class="hero"><div class="hero-grid"><div><span class="eyebrow">WELCOME BACK, EL HADJI</span><h2>Your business,<br>clearly in view.</h2><p>One place to see what is selling, what is blocked and what HUMBLE AFRICAN should do next.</p></div><div class="score"><span>OPERATING FOCUS</span><strong>REVENUE FIRST</strong><div class="progress"><span style="width:100%"></span></div></div></div></section>
 <section class="next-card"><div><span class="eyebrow">DO THIS NEXT</span><h3>${safeText(next?.task||"Review current sales and traffic")}</h3><small>${safeText(next?.why||"Use evidence to choose the next action.")}</small></div><button class="button large" data-go="today">Open next action →</button></section>
 <div class="status-grid"><article class="card status-card"><small>LIVE CHANNELS</small><h3>${live}</h3></article><article class="card status-card"><small>ACTIVE PRIORITIES</small><h3>${active}</h3></article><article class="card status-card"><small>BLOCKERS</small><h3>${blocked}</h3></article><article class="card status-card"><small>PRODUCT / COLLECTION RECORDS</small><h3>${data.illustrations.length}</h3></article></div>
 <div class="split"><section><div class="section-head"><div><h2>Priority actions</h2><p>Highest-value unfinished work.</p></div></div><div class="panel">${prioritizedTasks(data.tasks).slice(0,4).map(taskRow).join("")}</div></section><section><div class="section-head"><div><h2>Operating loop</h2><p>How HUMBLE AFRICAN grows.</p></div></div><div class="panel">${["1 · MARKET EVIDENCE","2 · EXISTING ASSETS","3 · EXECUTE & PUBLISH","4 · DRIVE TRAFFIC","5 · MEASURE & IMPROVE","6 · SCALE WHAT WORKS"].map(x=>`<div class="phase"><strong>${x}</strong></div>`).join("")}</div></section></div>${footer()}`;
}
function taskRow(t){return `<div class="task-row"><button class="task-check" data-done="${t.id}" title="Mark done">${t.status==="DONE"?"✓":""}</button><div class="task-main"><strong>${safeText(t.task)}</strong><small>${safeText(t.next)}</small></div>${pill(t.priority)}</div>`}
function renderToday(){const t=prioritizedTasks(data.tasks)[0];main.innerHTML=intro("Do This Next","The single highest-priority action. Finish or unblock this before adding more work.")+(t?`<article class="panel today-primary"><span class="eyebrow">CURRENT #1 PRIORITY</span><h2>${safeText(t.task)}</h2>${pill(t.status)}<h3>Why it matters</h3><p>${safeText(t.why)}</p><h3>Next action</h3><p>${safeText(t.next)}</p><h3>Steps</h3><ol class="steps">${t.steps.map(x=>`<li>${safeText(x)}</li>`).join("")}</ol><p><small>${safeText(t.blocker||t.notes)}</small></p><button class="button" data-done="${t.id}">Mark done</button></article>`:`<div class="panel empty">No unfinished priority tasks.</div>`)+footer()}
function renderTasks(){main.innerHTML=intro("Action Board","Current business priorities. Status changes are saved in this browser.")+`<div class="table-wrap"><table><thead><tr><th>ACTION</th><th>AREA</th><th>PRIORITY</th><th>STATUS</th><th>NEXT</th></tr></thead><tbody>${data.tasks.map(t=>`<tr><td><strong>${safeText(t.task)}</strong><br><small>${safeText(t.blocker)}</small></td><td>${safeText(t.category)}</td><td>${pill(t.priority)}</td><td><select data-task-status="${t.id}">${["NOT STARTED","IN PROGRESS","BLOCKED","DONE"].map(s=>`<option ${s===t.status?"selected":""}>${s}</option>`).join("")}</select></td><td>${safeText(t.next)}</td></tr>`).join("")}</tbody></table></div>${footer()}`}
function renderProducts(){main.innerHTML=intro("Products","Commercial products and collections currently represented in the business.")+`<div class="illustration-grid">${data.illustrations.map(x=>`<article class="card"><span class="eyebrow">PRODUCT / COLLECTION</span><h3>${safeText(x.name)}</h3>${pill(x.status)}<p>${safeText(x.notes)}</p></article>`).join("")}</div>${footer()}`}
function renderMarketplaces(){main.innerHTML=intro("Sales Channels","Where HUMBLE AFRICAN is selling, publishing or preparing to distribute.")+`<div class="market-grid">${data.marketplaces.map(m=>`<article class="card market-card"><h3>${safeText(m.name)}</h3><div>${pill(m.status)}</div><p><small>NEXT / OUTSTANDING</small><br>${safeText(m.outstanding)}</p><p>${safeText(m.notes)}</p>${m.url?`<a class="button secondary" href="${safeText(m.url)}" target="_blank" rel="noopener">Open channel</a>`:""}</article>`).join("")}</div>${footer()}`}
function renderKdp(){main.innerHTML=intro("Amazon KDP","Identity verification is the current KDP blocker. Do not store identity documents in this dashboard.")+`<div class="warning"><strong>Deadline:</strong> Complete KDP identity verification before 24 September 2026.</div><div class="panel">${data.kdp.map((x,i)=>`<div class="checklist-row"><strong>${safeText(x.name)}</strong><select data-kdp="${i}">${["NOT STARTED","IN PROGRESS","DONE","BLOCKED"].map(s=>`<option ${s===x.status?"selected":""}>${s}</option>`).join("")}</select></div>`).join("")}</div>${footer()}`}
function renderMarketing(){main.innerHTML=intro("Marketing","Track discovery and promotion without duplicating posts.")+`<div class="table-wrap"><table><thead><tr><th>CAMPAIGN</th><th>CHANNEL</th><th>STAGE</th></tr></thead><tbody>${data.marketing.map((x,i)=>`<tr><td><strong>${safeText(x.name)}</strong></td><td>${safeText(x.channel)}</td><td><select data-marketing="${i}">${["IDEA","SCRIPT","VISUALS","EDITED","SCHEDULED","PUBLISHED"].map(s=>`<option ${s===x.status?"selected":""}>${s}</option>`).join("")}</select></td></tr>`).join("")}</tbody></table></div>${footer()}`}
function renderTimeline(){main.innerHTML=intro("Milestones","Major business progress at a glance.")+`<div class="panel">${data.milestones.map((m,i)=>`<div class="task-row"><button class="task-check" data-milestone="${i}">${m.done?"✓":""}</button><div class="task-main"><strong>${safeText(m.name)}</strong><small>${safeText(m.date||"Not completed")}</small></div>${pill(m.done?"DONE":"NOT STARTED")}</div>`).join("")}</div>${footer()}`}
function renderDecisions(){main.innerHTML=intro("Operating Rules","Settled decisions that keep the business focused.")+`<div class="panel">${data.decisions.map(d=>`<div class="phase"><strong>${safeText(d.decision)}</strong><div>${safeText(d.notes)}</div><small>${safeText(d.reason)}</small></div>`).join("")}</div>${footer()}`}
const renders={overview:renderOverview,today:renderToday,tasks:renderTasks,products:renderProducts,marketplaces:renderMarketplaces,kdp:renderKdp,marketing:renderMarketing,timeline:renderTimeline,decisions:renderDecisions};
function route(){page=location.hash.slice(1)||"overview";if(!titles[page])page="overview";document.querySelector("#pageTitle").textContent=titles[page];renderNav();renders[page]();document.querySelector("#sidebar").classList.remove("open");window.scrollTo(0,0)}
document.addEventListener("click",e=>{const nav=e.target.closest("[data-page],[data-go]");if(nav){location.hash=nav.dataset.page||nav.dataset.go;return}const done=e.target.closest("[data-done]");if(done){const t=data.tasks.find(x=>x.id===done.dataset.done);if(t){t.status="DONE";save("Action completed");route()}return}const ms=e.target.closest("[data-milestone]");if(ms){const m=data.milestones[+ms.dataset.milestone];m.done=!m.done;save();route()}});
document.addEventListener("change",e=>{if(e.target.matches("[data-task-status]")){data.tasks.find(x=>x.id===e.target.dataset.taskStatus).status=e.target.value;save()}if(e.target.matches("[data-kdp]")){data.kdp[+e.target.dataset.kdp].status=e.target.value;save()}if(e.target.matches("[data-marketing]")){data.marketing[+e.target.dataset.marketing].status=e.target.value;save()}});
document.querySelector("#menuButton")?.addEventListener("click",()=>document.querySelector("#sidebar").classList.toggle("open"));
document.querySelector("#backupButton")?.addEventListener("click",()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="humble-african-command-centre-backup.json";a.click();URL.revokeObjectURL(a.href)});
window.addEventListener("hashchange",route);route();
