import { initialData } from "./data.js";
import { readiness, prioritizedTasks, categoryStatus, safeText } from "./logic.js";

const STORAGE_KEY = "aisha-command-centre-v1";
const clone = value => JSON.parse(JSON.stringify(value));
let data = load();
let page = location.hash.slice(1) || "overview";

const pages = [
  ["FOCUS",[["overview","⌂","Overview"],["today","☀","Today"],["tasks","✓","Master Tasks"]]],
  ["THE BOOK",[["files","▤","Book Files"],["quality","◇","File Quality"],["metadata","✎","Book Information"],["illustrations","▧","Illustrations"],["characters","♙","Character Bible"]]],
  ["PUBLISH & SELL",[["marketplaces","◎","Marketplaces"],["kdp","K","Amazon KDP"],["korakite","K","KoraKite"],["shopify","S","Shopify"]]],
  ["PROMOTE & PLAN",[["marketing","◉","Marketing"],["episodes","▶","Video Episodes"],["timeline","◷","Timeline"],["decisions","□","Decisions"]]]
];
const titles = Object.fromEntries(pages.flatMap(g=>g[1]).map(x=>[x[0],x[2]]));
const main = document.querySelector("main");

function load(){try{return {...clone(initialData),...JSON.parse(localStorage.getItem(STORAGE_KEY)||"{}")}}catch{return clone(initialData)}}
function save(message="Saved"){localStorage.setItem(STORAGE_KEY,JSON.stringify(data));toast(message)}
function toast(message){const el=document.querySelector("#toast");el.textContent=message;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),1800)}
function statusClass(s){return s.toLowerCase().replaceAll(" ","-")}
function pill(s){return `<span class="pill ${statusClass(s)}">${safeText(s)}</span>`}
function intro(title,copy,action=""){return `<div class="page-intro"><div class="section-head"><div><h2>${title}</h2><p>${copy}</p></div>${action}</div></div>`}
function select(options,value,attrs=""){return `<select ${attrs}>${options.map(x=>`<option ${x===value?"selected":""}>${x}</option>`).join("")}</select>`}

function renderNav(){document.querySelector("#navigation").innerHTML=pages.map(([label,items])=>`<div class="nav-group"><div class="nav-label">${label}</div>${items.map(([id,icon,name])=>`<button class="nav-button ${page===id?"active":""}" data-page="${id}"><span class="nav-icon">${icon}</span>${name}</button>`).join("")}</div>`).join("")}
function route(){page=location.hash.slice(1)||"overview";if(!titles[page])page="overview";document.querySelector("#pageTitle").textContent=titles[page];renderNav();(renders[page]||renderOverview)();document.querySelector("#sidebar").classList.remove("open");window.scrollTo(0,0)}

function renderOverview(){
  const score=readiness(data.tasks), next=prioritizedTasks(data.tasks)[0];
  main.innerHTML=`<section class="hero"><div class="hero-grid"><div><span class="eyebrow">WELCOME BACK, EL HADJI</span><h2>Your publishing journey,<br>clearly in view.</h2><p>One calm place to prepare, publish and share Aisha's story. Your information is saved on this device.</p></div><div class="score"><span>PUBLICATION READINESS</span><strong>${score}%</strong><div class="progress"><span style="width:${score}%"></span></div></div></div></section>
  <section class="next-card"><div><span class="eyebrow">RECOMMENDED NEXT STEP</span><h3>${safeText(next?.task||"All current tasks are complete")}</h3><small>${safeText(next?.why||"You are ready to add the next publishing goal.")}</small></div><button class="button large" data-next>What should I do next? →</button></section>
  <div class="section-head"><div><h2>Project at a glance</h2><p>Five areas that make up publication readiness.</p></div></div><div class="status-grid">${["BOOK","ILLUSTRATIONS","PUBLISHING","STORE","MARKETING"].map(cat=>{const s=categoryStatus(data.tasks,cat);return `<article class="card status-card"><small>${cat}</small><h3><i class="status-dot ${statusClass(s)}"></i>${s}</h3></article>`}).join("")}</div>
  <div class="split"><section><div class="section-head"><div><h2>Priority tasks</h2><p>The most useful work, in order.</p></div><button class="button secondary" data-go="tasks">View all</button></div><div class="panel">${prioritizedTasks(data.tasks).slice(0,3).map(taskRow).join("")}</div></section><section><div class="section-head"><div><h2>Publishing route</h2><p>Focus on one phase at a time.</p></div></div><div class="panel">${[[1,"Amazon ebook · Payhip · KoraKite"],[2,"Amazon paperback · Shopify"],[3,"Draft2Digital · Etsy bundle"],[4,"IngramSpark after print and ISBN decisions"]].map(x=>`<div class="phase"><strong>PHASE ${x[0]}</strong><div>${x[1]}</div></div>`).join("")}</div></section></div>${footer()}`;
}
function taskRow(t){return `<div class="task-row"><button class="task-check" data-done="${t.id}" title="Mark done">${t.status==="DONE"?"✓":""}</button><div class="task-main"><strong>${safeText(t.task)}</strong><small>${safeText(t.category)} · ${safeText(t.next)}</small></div>${pill(t.priority)}</div>`}
function renderToday(){const tasks=prioritizedTasks(data.tasks).slice(0,3),first=tasks[0];main.innerHTML=intro("Today","Only the three most important tasks. Finish the first before worrying about the rest.")+(!first?`<div class="panel empty">All current tasks are complete.</div>`:`<article class="panel today-primary"><span class="eyebrow">TODAY'S #1 PRIORITY</span><h2>${safeText(first.task)}</h2>${pill(first.status)}<h3>Why this matters</h3><p>${safeText(first.why)}</p><h3>Do this now</h3><ol class="steps">${first.steps.map(x=>`<li>${safeText(x)}</li>`).join("")}</ol><button class="button" data-done="${first.id}">Mark this task done</button></article>${tasks.slice(1).map((t,i)=>`<article class="card" style="margin-top:14px"><span class="eyebrow">TASK ${i+2}</span><h3>${safeText(t.task)}</h3><p>${safeText(t.next)}</p></article>`).join("")}`)+footer()}
function renderTasks(){main.innerHTML=intro("Master Task Manager","See every task, or narrow the list using the simple filters.",`<button class="button" data-add-task>+ Add task</button>`)+`<div class="toolbar">${select(["ALL CATEGORIES","BOOK","ILLUSTRATIONS","PUBLISHING","STORE","MARKETING"],"ALL CATEGORIES",'id="categoryFilter"')}${select(["ALL STATUSES","NOT STARTED","IN PROGRESS","BLOCKED","DONE"],"ALL STATUSES",'id="statusFilter"')}</div><div class="table-wrap"><table><thead><tr><th>TASK</th><th>CATEGORY</th><th>PRIORITY</th><th>STATUS</th><th>NEXT ACTION</th></tr></thead><tbody id="taskBody">${taskRows(data.tasks)}</tbody></table></div>${footer()}`}
function taskRows(list){return list.map(t=>`<tr><td><strong>${safeText(t.task)}</strong><br><small>${safeText(t.blocker||t.notes)}</small></td><td>${t.category}</td><td>${pill(t.priority)}</td><td>${select(["NOT STARTED","IN PROGRESS","BLOCKED","DONE"],t.status,`data-task-status="${t.id}"`)}</td><td>${safeText(t.next)}</td></tr>`).join("")}
function renderFiles(){main.innerHTML=intro("Book Files","Register where important files are kept. The app records the file name and does not alter your original.",`<button class="button" data-add-file>+ Add file</button>`)+(data.files.length?`<div class="table-wrap"><table><thead><tr><th>FILE</th><th>TYPE & PURPOSE</th><th>ADDED</th><th>STATUS</th><th>MARKETPLACE USE</th></tr></thead><tbody>${data.files.map(f=>`<tr><td><strong>${safeText(f.name)}</strong><br><small>${safeText(f.notes)}</small></td><td>${pill(f.type)}<br>${safeText(f.purpose)}</td><td>${safeText(f.date)}</td><td>${safeText(f.status)}</td><td>${safeText(f.marketplace)}</td></tr>`).join("")}</tbody></table></div>`:`<div class="panel empty"><h3>No files registered yet</h3><p>Your original files remain safely where they are. Add a record so you know which version belongs where.</p><button class="button" data-add-file>Add your first file</button></div>`)+footer()}
function renderQuality(){const section=(key,title)=>`<section class="panel"><h2>${title}</h2>${data.quality[key].map(name=>`<div class="checklist-row"><span>${name}</span>${select(["NOT AVAILABLE","NEEDS ATTENTION","READY"],data.qualityStates[key+name]||"NOT AVAILABLE",`data-quality="${key+name}"`)}</div>`).join("")}</section>`;main.innerHTML=intro("File Quality Check","A calm final check before any file is submitted.")+`<div class="quality-grid">${section("epub","Ebook (EPUB)")}${section("paperback","Paperback")}</div>${footer()}`}
function renderMetadata(){main.innerHTML=intro("Master Book Information","The single trusted place for book details. Do not guess—leave uncertain information unconfirmed.")+`<form class="panel metadata-grid" id="metadataForm">${Object.entries(data.metadata).map(([k,v])=>`<div class="field ${k.includes("description")?"wide":""}"><label>${k}</label>${k.includes("description")?`<textarea name="${safeText(k)}">${safeText(v)}</textarea>`:`<input name="${safeText(k)}" value="${safeText(v)}">`}</div>`).join("")}<div class="wide"><button class="button">Save book information</button></div></form>${footer()}`}

function renderMarketplaces(){main.innerHTML=intro("Marketplace Control Centre","Follow the phases. You do not need to set up every store at once.")+`<div class="market-grid">${data.marketplaces.map((m,i)=>`<article class="card market-card"><span class="phase-tag">PHASE ${m.phase}</span><h3>${safeText(m.name)}</h3><div style="margin-top:7px">${pill(m.status)}</div><div class="details"><div><small>Account</small>${m.account}</div><div><small>Book uploaded</small>${m.book}</div><div><small>Cover</small>${m.cover}</div><div><small>Published</small>${m.published}</div></div><p><small>OUTSTANDING</small><br>${safeText(m.outstanding)}</p><button class="button secondary" data-market="${i}">Update marketplace</button></article>`).join("")}</div>${footer()}`}
function workflow(title,copy,key,warning=""){main.innerHTML=intro(title,copy)+warning+`<div class="panel">${data[key].map((x,i)=>`<div class="checklist-row"><strong>${safeText(x.name)}</strong>${select(["NOT STARTED","IN PROGRESS","DONE","BLOCKED"],x.status,`data-flow="${key}" data-index="${i}"`)}</div>`).join("")}</div>${footer()}`}
function renderKdp(){workflow("Amazon KDP","Complete the ebook workflow in order. Nothing here submits the book to Amazon.","kdp")}
function renderKorakite(){const disconnected=data.korakite.find(x=>x.name==="Aisha library page")?.status==="DONE"&&data.korakite.find(x=>x.name==="Download link")?.status!=="DONE";workflow("KoraKite","Track the public Aisha page and customer delivery.","korakite",disconnected?`<div class="warning"><strong>Action needed:</strong> The public page exists, but the downloadable book has not yet been connected. Visitors cannot receive the final ebook yet.</div>`:"")}
function renderShopify(){workflow("Shopify","Track the product and checkout without storing private bank details.","shopify",`<div class="warning">For safety, this app only records whether the payout account is verified. Never enter bank numbers or passwords here.</div>`)}

function renderIllustrations(){main.innerHTML=intro("Illustration Control","Keep every visual consistent from first prompt to final artwork.")+`<div class="illustration-grid">${data.illustrations.map((x,i)=>`<article class="card"><div style="height:110px;background:#ece8dc;border-radius:9px;display:grid;place-items:center;color:#8a8c86">${x.preview?`<img src="${safeText(x.preview)}" alt="${safeText(x.name)}" style="max-height:100%;max-width:100%">`:"Image preview"}</div><h3>${safeText(x.name)}</h3>${select(["NOT STARTED","PROMPT READY","GENERATED","APPROVED","FINAL"],x.status,`data-illustration="${i}"`)}<p><small>Final filename</small><br>${safeText(x.filename||"TO BE CONFIRMED")}</p></article>`).join("")}</div>${footer()}`}
function renderCharacters(){main.innerHTML=intro("Character Bible","Protect visual consistency. Missing creative details are deliberately left for you to confirm.")+`<div class="illustration-grid">${data.characters.map((c,i)=>`<article class="card"><span class="eyebrow">CHARACTER REFERENCE</span><h3>${safeText(c.name)}</h3><p><small>AGE</small><br>${safeText(c.age)}</p><p><small>APPEARANCE</small><br>${safeText(c.description)}</p><p><small>RELATIONSHIP TO AISHA</small><br>${safeText(c.relationship)}</p><button class="button secondary" data-character="${i}">View & edit details</button></article>`).join("")}</div>${footer()}`}
function renderMarketing(){main.innerHTML=intro("Marketing Command Centre","Move each idea forward one simple stage at a time.")+`<div class="table-wrap"><table><thead><tr><th>ASSET</th><th>CHANNEL</th><th>STAGE</th></tr></thead><tbody>${data.marketing.map((x,i)=>`<tr><td><strong>${safeText(x.name)}</strong></td><td>${safeText(x.channel)}</td><td>${select(["IDEA","SCRIPT","VISUALS","VOICEOVER","EDITED","SCHEDULED","PUBLISHED"],x.status,`data-marketing="${i}"`)}</td></tr>`).join("")}</tbody></table></div>${footer()}`}
function renderEpisodes(){main.innerHTML=intro("10-Part Video Series","Plan faceless Aisha story videos without needing to appear on camera.")+`<div class="illustration-grid">${data.episodes.map((e,i)=>`<article class="card"><span class="eyebrow">EPISODE ${e.number}</span><h3>${safeText(e.title)}</h3>${pill(e.status)}<p>${safeText(e.hook||"Hook not written yet")}</p><button class="button secondary" data-episode="${i}">Plan episode</button></article>`).join("")}</div>${footer()}`}
function renderTimeline(){main.innerHTML=intro("Project Timeline","A simple path from manuscript to launch.")+`<div class="panel">${data.milestones.map((m,i)=>`<div class="task-row"><button class="task-check" data-milestone="${i}">${m.done?"✓":""}</button><div class="task-main"><strong>${m.name}</strong><small>${m.done?(m.date||"Completed — date not recorded"):"Not completed yet"}</small></div>${pill(m.done?"DONE":"NOT STARTED")}</div>`).join("")}</div>${footer()}`}
function renderDecisions(){main.innerHTML=intro("Notes & Decisions","Record settled choices so you do not have to reconsider them later.",`<button class="button" data-add-decision>+ Record decision</button>`)+`<div class="table-wrap"><table><thead><tr><th>DECISION</th><th>DATE</th><th>REASON</th><th>STATUS</th><th>NOTES</th></tr></thead><tbody>${data.decisions.map(d=>`<tr><td><strong>${safeText(d.decision)}</strong></td><td>${safeText(d.date||"Not recorded")}</td><td>${safeText(d.reason)}</td><td>${pill(d.status)}</td><td>${safeText(d.notes)}</td></tr>`).join("")}</tbody></table></div>${footer()}`}
function footer(){return `<div class="footer-note">Saved on this device · Nothing is sent, purchased or published automatically.</div>`}

const renders={overview:renderOverview,today:renderToday,tasks:renderTasks,files:renderFiles,quality:renderQuality,metadata:renderMetadata,marketplaces:renderMarketplaces,kdp:renderKdp,korakite:renderKorakite,shopify:renderShopify,illustrations:renderIllustrations,characters:renderCharacters,marketing:renderMarketing,episodes:renderEpisodes,timeline:renderTimeline,decisions:renderDecisions};
function modal(title,body){const layer=document.querySelector("#modalLayer");layer.innerHTML=`<div class="modal" role="dialog" aria-modal="true" aria-label="${safeText(title)}"><div class="modal-head"><h2>${safeText(title)}</h2><button class="close" data-close aria-label="Close">×</button></div>${body}</div>`;layer.hidden=false;layer.querySelector("input,select,button")?.focus()}
function closeModal(){document.querySelector("#modalLayer").hidden=true}
function nextModal(){const t=prioritizedTasks(data.tasks)[0];modal("Your next action",t?`<span class="eyebrow">NEXT ACTION</span><h3>${safeText(t.task)}</h3><h4>Why</h4><p>${safeText(t.why)}</p><h4>Do this now</h4><ol class="steps">${t.steps.map(x=>`<li>${safeText(x)}</li>`).join("")}</ol><button class="button" data-done="${t.id}">Mark done</button>`:`<p>All current tasks are complete.</p>`)}
function addFile(){modal("Add a book file",`<form id="fileForm" class="form-grid"><div class="field wide"><label>File name</label><input name="name" required placeholder="Example: Aisha_final.epub"></div><div class="field"><label>File type</label>${select(["MANUSCRIPT","EPUB","PRINT PDF","COVER","ILLUSTRATION","MARKETING","ARCHIVE","OTHER"],"EPUB",'name="type"')}</div><div class="field"><label>Status</label>${select(["DRAFT","NEEDS ATTENTION","READY","ARCHIVED"],"READY",'name="status"')}</div><div class="field wide"><label>Purpose</label><input name="purpose" required placeholder="What is this file for?"></div><div class="field"><label>Marketplace use</label><input name="marketplace" placeholder="Example: Amazon KDP"></div><div class="field"><label>Date added</label><input type="date" name="date" value="${new Date().toISOString().slice(0,10)}"></div><div class="field wide"><label>Notes</label><textarea name="notes"></textarea></div><div class="wide"><button class="button">Register file</button></div></form>`)}
function addTask(){modal("Add a task",`<form id="taskForm" class="form-grid"><div class="field wide"><label>Task</label><input name="task" required></div><div class="field"><label>Category</label>${select(["BOOK","ILLUSTRATIONS","PUBLISHING","STORE","MARKETING"],"BOOK",'name="category"')}</div><div class="field"><label>Priority</label>${select(["CRITICAL","HIGH","NORMAL","LATER"],"NORMAL",'name="priority"')}</div><div class="field wide"><label>Next action</label><input name="next" required></div><div class="field wide"><label>Why this matters</label><textarea name="why" required></textarea></div><button class="button">Add task</button></form>`)}
function updateMarket(i){const m=data.marketplaces[i];modal(`Update ${m.name}`,`<form id="marketForm" data-index="${i}" class="form-grid"><div class="field"><label>Status</label>${select(["NOT STARTED","ACCOUNT CREATED","SETTING UP","READY TO UPLOAD","SUBMITTED","LIVE","BLOCKED"],m.status,'name="status"')}</div>${[["account","Account created"],["book","Book uploaded"],["cover","Cover uploaded"],["description","Description ready"],["price","Price entered"],["payment","Payment setup"],["published","Published"]].map(([n,l])=>`<div class="field"><label>${l}</label>${select(["NO","YES"],m[n],`name="${n}"`)}</div>`).join("")}<div class="field wide"><label>Store / product link</label><input name="url" value="${safeText(m.url)}"></div><div class="field wide"><label>Outstanding tasks</label><textarea name="outstanding">${safeText(m.outstanding)}</textarea></div><div class="field wide"><label>Notes</label><textarea name="notes">${safeText(m.notes)}</textarea></div><button class="button">Save update</button></form>`)}
function editCharacter(i){const c=data.characters[i], fields=[["age","Age"],["description","Physical description"],["clothing","Clothing"],["colours","Colours"],["hair","Hair"],["objects","Important objects"],["personality","Personality"],["relationship","Relationship to Aisha"],["rules","Visual consistency rules"],["image","Approved reference image location"]];modal(`${c.name} reference`, `<form id="characterForm" data-index="${i}" class="form-grid">${fields.map(([n,l])=>`<div class="field ${["description","rules"].includes(n)?"wide":""}"><label>${l}</label><input name="${n}" value="${safeText(c[n])}"></div>`).join("")}<button class="button">Save reference</button></form>`)}
function editEpisode(i){const e=data.episodes[i],fields=[["title","Title"],["hook","Hook"],["voiceover","Voiceover"],["scenes","Scene list"],["imagePrompts","Image prompts"],["videoPrompts","Video prompts"],["sound","Sound effects"],["music","Music notes"],["thumbnail","Thumbnail"],["description","Description"],["tags","Tags"]];modal(`Plan episode ${e.number}`,`<form id="episodeForm" data-index="${i}" class="form-grid">${fields.map(([n,l])=>`<div class="field ${["voiceover","scenes","imagePrompts","videoPrompts","description"].includes(n)?"wide":""}"><label>${l}</label><textarea name="${n}">${safeText(e[n])}</textarea></div>`).join("")}<div class="field"><label>Status</label>${select(["IDEA","SCRIPT","VISUALS","VOICEOVER","EDITED","SCHEDULED","PUBLISHED"],e.status,'name="status"')}</div><button class="button">Save episode</button></form>`)}
function addDecision(){modal("Record a decision",`<form id="decisionForm" class="form-grid"><div class="field wide"><label>Decision</label><input name="decision" required></div><div class="field"><label>Date</label><input type="date" name="date" value="${new Date().toISOString().slice(0,10)}"></div><div class="field"><label>Status</label>${select(["NEEDS CONFIRMATION","CONFIRMED","REVISIT LATER"],"CONFIRMED",'name="status"')}</div><div class="field wide"><label>Reason</label><textarea name="reason" required></textarea></div><div class="field wide"><label>Notes</label><textarea name="notes"></textarea></div><button class="button">Record decision</button></form>`)}

document.addEventListener("click",e=>{const el=e.target.closest("button");if(!el)return;if(el.dataset.page)location.hash=el.dataset.page;if(el.dataset.go)location.hash=el.dataset.go;if(el.hasAttribute("data-next"))nextModal();if(el.hasAttribute("data-close"))closeModal();if(el.hasAttribute("data-add-file"))addFile();if(el.hasAttribute("data-add-task"))addTask();if(el.hasAttribute("data-add-decision"))addDecision();if(el.dataset.market!==undefined)updateMarket(+el.dataset.market);if(el.dataset.character!==undefined)editCharacter(+el.dataset.character);if(el.dataset.episode!==undefined)editEpisode(+el.dataset.episode);if(el.dataset.done){const t=data.tasks.find(x=>x.id===el.dataset.done);t.status="DONE";save("Task completed");closeModal();route()}if(el.dataset.milestone!==undefined){const m=data.milestones[+el.dataset.milestone];m.done=!m.done;m.date=m.done?new Date().toISOString().slice(0,10):"";save();route()}if(el.id==="menuButton")document.querySelector("#sidebar").classList.toggle("open")});
document.addEventListener("change",e=>{if(e.target.dataset.taskStatus){data.tasks.find(x=>x.id===e.target.dataset.taskStatus).status=e.target.value;save();}if(e.target.dataset.quality){data.qualityStates[e.target.dataset.quality]=e.target.value;save()}if(e.target.dataset.flow){data[e.target.dataset.flow][+e.target.dataset.index].status=e.target.value;save()}if(e.target.dataset.illustration!==undefined){data.illustrations[+e.target.dataset.illustration].status=e.target.value;save()}if(e.target.dataset.marketing!==undefined){data.marketing[+e.target.dataset.marketing].status=e.target.value;save()}if(["categoryFilter","statusFilter"].includes(e.target.id)){const c=document.querySelector("#categoryFilter").value,s=document.querySelector("#statusFilter").value;document.querySelector("#taskBody").innerHTML=taskRows(data.tasks.filter(t=>(c==="ALL CATEGORIES"||t.category===c)&&(s==="ALL STATUSES"||t.status===s)))}});
document.addEventListener("submit",e=>{e.preventDefault();const f=e.target, values=Object.fromEntries(new FormData(f));if(f.id==="metadataForm"){data.metadata=values;save("Book information saved");}if(f.id==="fileForm"){data.files.push({...values,id:crypto.randomUUID()});save("File registered safely");closeModal();renderFiles()}if(f.id==="taskForm"){data.tasks.push({...values,id:crypto.randomUUID(),status:"NOT STARTED",blocker:"",steps:[values.next],notes:"",order:data.tasks.length+1});save("Task added");closeModal();renderTasks()}if(f.id==="marketForm"){Object.assign(data.marketplaces[+f.dataset.index],values);save("Marketplace updated");closeModal();renderMarketplaces()}if(f.id==="characterForm"){Object.assign(data.characters[+f.dataset.index],values);save("Character reference saved");closeModal();renderCharacters()}if(f.id==="episodeForm"){Object.assign(data.episodes[+f.dataset.index],values);save("Episode plan saved");closeModal();renderEpisodes()}if(f.id==="decisionForm"){data.decisions.push({...values,id:crypto.randomUUID()});save("Decision recorded");closeModal();renderDecisions()}});
document.querySelector("#backupButton").addEventListener("click",()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`Aisha_Project_Backup_${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);toast("Project backup downloaded")});
window.addEventListener("hashchange",route);route();
