export const initialData = {
  metadata: {
    Title: "Aisha", Subtitle: "A Daughter of the Savannah", Author: "EL HADJI", Edition: "TO BE CONFIRMED", Language: "English", "Reader age": "8–12", "Book description": "An illustrated children's chapter book about family, community, the savannah, environmental responsibility, resilience, learning and community action.", "Short description": "A young girl and a traveller unite traditional wisdom and practical action to help a drought-stricken savannah community restore hope.", Keywords: "TO BE CONFIRMED", Categories: "TO BE CONFIRMED", "Publisher / imprint": "TO BE CONFIRMED", ISBN: "TO BE CONFIRMED", "Publication date": "TO BE CONFIRMED", "Ebook price": "TO BE CONFIRMED", "Paperback price": "TO BE CONFIRMED", Copyright: "TO BE CONFIRMED", "Rights territories": "TO BE CONFIRMED"
  },
  tasks: [
    {id:"t1",task:"Confirm the final ebook file",category:"BOOK",priority:"CRITICAL",status:"IN PROGRESS",blocker:"The final EPUB has not been registered.",next:"Find the latest EPUB, check that it opens, then add it to Book Files.",why:"Every Phase 1 store needs the final ebook before publication can move forward.",steps:["Find the latest Aisha EPUB on your computer","Open it and check the first and last pages","Use Book Files → Add file to register it"],notes:"Do not replace an earlier version; register the final copy separately.",order:1},
    {id:"t2",task:"Approve the final ebook cover",category:"ILLUSTRATIONS",priority:"HIGH",status:"NOT STARTED",blocker:"",next:"Choose and register the approved cover.",why:"Amazon, Payhip and KoraKite all need one approved cover.",steps:["Review the latest cover","Confirm the title and author are correct","Register the approved image in Book Files"],notes:"",order:2},
    {id:"t3",task:"Complete the master book information",category:"PUBLISHING",priority:"HIGH",status:"IN PROGRESS",blocker:"Price, publication details, ISBN, imprint, categories and keywords need confirmation.",next:"Resolve the manuscript title mismatch, then approve the remaining commercial details.",why:"The same accurate details should appear in every store.",steps:["Confirm which manuscript is the final master","Resolve the incorrect title inside the 22 September document","Approve only verified commercial details"],notes:"English, reader age and the working title are now recorded from the approved project sources.",order:3},
    {id:"t4",task:"Prepare Amazon KDP ebook listing",category:"STORE",priority:"HIGH",status:"NOT STARTED",blocker:"Final EPUB and cover are needed first.",next:"Complete the Book Details section.",why:"Amazon KDP is a Phase 1 priority route to readers.",steps:["Confirm your KDP account","Enter the approved book details","Stop before submission until files are ready"],notes:"Never submit without explicit approval.",order:4},
    {id:"t5",task:"Prepare the launch announcement",category:"MARKETING",priority:"NORMAL",status:"NOT STARTED",blocker:"Publication date is not confirmed.",next:"Draft a reusable announcement without a date.",why:"A prepared announcement makes launch day calmer.",steps:["Write a short introduction to Aisha","Add the approved cover later","Do not schedule until the date is confirmed"],notes:"",order:5}
  ],
  files: [
    {id:"f1",name:"Copy of (Aisha Savannah, The Dreamer)",type:"SOURCE DOCUMENT",purpose:"Earlier story source: family, community, camel relationships and character foundations",date:"2026-09-09",status:"REVIEWED — NOT FINAL",marketplace:"Internal reference only",notes:"Private source record; no Drive link or manuscript text is stored here."},
    {id:"f2",name:"Untitled document — Aisha expansion notes",type:"EDITORIAL NOTES",purpose:"World-building, character development, conflict, dialogue and pacing guidance",date:"2026-09-09",status:"REVIEWED",marketplace:"Internal reference only",notes:"Planning source, not a publication file."},
    {id:"f3",name:"Untitled — modified 22 September 2025",type:"MANUSCRIPT CANDIDATE",purpose:"Expanded Aisha chapter structure and illustration directions",date:"2026-09-09",status:"BLOCKED — TITLE MISMATCH",marketplace:"Do not upload",notes:"The file currently begins with “One Thousand Roads to Mecca.” Confirm and correct the master before publication."}
  ],
  quality: {
    epub:["EPUB available","Cover available","Title confirmed","Author confirmed","Language confirmed","Metadata reviewed","Description prepared","Pricing prepared"],
    paperback:["Interior PDF available","Trim size confirmed","Page count confirmed","Cover wrap available","ISBN decision completed","Print settings confirmed","Proof ordered","Proof approved"]
  },
  qualityStates:{},
  marketplaces: [
    {name:"Amazon KDP",phase:1,status:"NOT STARTED",account:"NO",book:"NO",cover:"NO",description:"NO",price:"NO",payment:"NO",published:"NO",url:"",outstanding:"Final ebook, cover and metadata",notes:"Phase 1: ebook first"},
    {name:"Payhip",phase:1,status:"NOT STARTED",account:"NO",book:"NO",cover:"NO",description:"NO",price:"NO",payment:"NO",published:"NO",url:"",outstanding:"Set up direct ebook product",notes:"Phase 1"},
    {name:"KoraKite",phase:1,status:"SETTING UP",account:"YES",book:"NO",cover:"NO",description:"NO",price:"NO",payment:"NO",published:"NO",url:"",outstanding:"Connect the final downloadable ebook",notes:"Public page may already exist"},
    {name:"Amazon paperback",phase:2,status:"NOT STARTED",account:"YES",book:"NO",cover:"NO",description:"NO",price:"NO",payment:"NO",published:"NO",url:"",outstanding:"Complete print files and proof",notes:"Phase 2"},
    {name:"Shopify",phase:2,status:"NOT STARTED",account:"NO",book:"NO",cover:"NO",description:"NO",price:"NO",payment:"NO",published:"NO",url:"",outstanding:"Verify store and payouts",notes:"Phase 2"},
    {name:"Draft2Digital",phase:3,status:"NOT STARTED",account:"NO",book:"NO",cover:"NO",description:"NO",price:"NO",payment:"NO",published:"NO",url:"",outstanding:"Wait until Phase 1 is complete",notes:"Phase 3"},
    {name:"Etsy",phase:3,status:"NOT STARTED",account:"NO",book:"NO",cover:"NO",description:"NO",price:"NO",payment:"NO",published:"NO",url:"",outstanding:"Plan educational/family bundle",notes:"Phase 3"},
    {name:"IngramSpark",phase:4,status:"BLOCKED",account:"NO",book:"NO",cover:"NO",description:"NO",price:"NO",payment:"NO",published:"NO",url:"",outstanding:"Settle print edition and ISBN strategy",notes:"Phase 4"}
  ],
  kdp:["ACCOUNT","BOOK DETAILS","MANUSCRIPT","COVER","PRICING","RIGHTS","PREVIEW","SUBMISSION"].map((name,i)=>({name,status:i===0?"IN PROGRESS":"NOT STARTED"})),
  korakite:["Aisha library page","Story previews","Interest form","Final ebook","Download link","Product page","Price","Customer delivery","Testing"].map((name,i)=>({name,status:i<3?"DONE":"NOT STARTED"})),
  shopify:["Store active","Business verification","Payout account verified","Payments active","Aisha product created","Cover uploaded","Description","Digital file attached","Price","Checkout tested","Confirmation email tested","Product live"].map(name=>({name,status:"NOT STARTED"})),
  illustrations:["Cover","Aisha character reference","Omar","Fatima","Karim","Mariama","Zahra","Elara","Savannah establishing scenes","Village/community scenes","Environmental restoration scenes","Chapter illustrations","Marketing artwork"].map((name,i)=>({name,status:i===0?"PROMPT READY":"NOT STARTED",prompt:"",notes:"",location:"",filename:"",preview:""})),
  characters:[
    {name:"Aisha",age:"TO BE CONFIRMED",description:"A young camel herder connected deeply to her family, community and the savannah.",clothing:"TO BE CONFIRMED",colours:"TO BE CONFIRMED",hair:"TO BE CONFIRMED",objects:"Water vessel; camel-herding tools",personality:"Observant, compassionate, determined and hopeful",relationship:"Main character; daughter of Omar and Fatima; older sister of Karim",rules:"Keep her age, appearance and clothing consistent after approval.",image:""},
    {name:"Omar",age:"TO BE CONFIRMED",description:"Aisha's father and an experienced camel herder.",clothing:"TO BE CONFIRMED",colours:"TO BE CONFIRMED",hair:"TO BE CONFIRMED",objects:"Camel-herding tools",personality:"Practical and shaped by the wisdom of the land",relationship:"Aisha's father; Fatima's partner",rules:"Do not invent physical details before approval.",image:""},
    {name:"Fatima",age:"TO BE CONFIRMED",description:"Aisha's mother, a skilled weaver and keeper of traditional stories.",clothing:"TO BE CONFIRMED",colours:"TO BE CONFIRMED",hair:"TO BE CONFIRMED",objects:"Weaving materials",personality:"Resourceful, nurturing and knowledgeable",relationship:"Aisha and Karim's mother; Omar's partner",rules:"Do not invent physical details before approval.",image:""},
    {name:"Karim",age:"TO BE CONFIRMED",description:"Aisha's playful younger brother.",clothing:"TO BE CONFIRMED",colours:"TO BE CONFIRMED",hair:"TO BE CONFIRMED",objects:"TO BE CONFIRMED",personality:"Mischievous and curious",relationship:"Aisha's younger brother",rules:"Do not invent physical details before approval.",image:""},
    {name:"Mariama",age:"Elder",description:"A respected village elder who shares memories of a greener savannah.",clothing:"TO BE CONFIRMED",colours:"TO BE CONFIRMED",hair:"TO BE CONFIRMED",objects:"TO BE CONFIRMED",personality:"Wise, perceptive and firm",relationship:"Community elder and mentor to Aisha",rules:"Name differs from “Elder Mala” in another draft; resolve before final production.",image:""},
    {name:"Zahra",age:"TO BE CONFIRMED",description:"A camel especially close to Aisha and treated as part of her family.",clothing:"Not applicable",colours:"TO BE CONFIRMED",hair:"TO BE CONFIRMED",objects:"TO BE CONFIRMED",personality:"Trusted companion",relationship:"Aisha's favourite camel",rules:"Another draft uses the camel name “Jabari”; resolve before final production.",image:""},
    {name:"Elara",age:"Adult",description:"A traveller who brings knowledge from distant places and works alongside Aisha's community.",clothing:"TO BE CONFIRMED",colours:"Deep blues and reds appear in one draft; approval required",hair:"TO BE CONFIRMED",objects:"Backpack, books, maps, tools and walking staff vary by draft",personality:"Curious, empathetic, resourceful and committed",relationship:"Aisha's friend and collaborator",rules:"Confirm her approved backstory, appearance and objects before illustration.",image:""}
  ],
  marketing:["Book trailer","Short videos","Character introductions","Story excerpts","Educational posts","Behind-the-scenes content","Launch announcement","Cover reveal","Author introduction","Product images"].map((name,i)=>({name,channel:["YouTube","YouTube Shorts","TikTok","Instagram","Facebook","Email","Shopify","KoraKite"][i%8],status:"IDEA"})),
  episodes:Array.from({length:10},(_,i)=>({number:i+1,title:"TO BE CONFIRMED",hook:"",voiceover:"",scenes:"",imagePrompts:"",videoPrompts:"",sound:"",music:"",thumbnail:"",description:"",tags:"",status:"IDEA"})),
  milestones:["MANUSCRIPT COMPLETE","PUBLISHING FILES COMPLETE","KDP EBOOK SUBMITTED","KDP EBOOK LIVE","PAYHIP LIVE","KORAKITE LIVE","PAPERBACK PROOF ORDERED","PAPERBACK APPROVED","SHOPIFY LIVE","MARKETING LAUNCH"].map(name=>({name,done:false,date:""})),
  decisions:[
    {id:"d1",decision:"Final title approved",date:"",reason:"Title supplied for this project",status:"CONFIRMED",notes:"Aisha: A Daughter of the Savannah"},
    {id:"d2",decision:"Reader age approved",date:"",reason:"Primary reader age supplied as approximately 8–12",status:"NEEDS CONFIRMATION",notes:"Confirm before marketplace submission"},
    {id:"d3",decision:"Use English as the working manuscript language",date:"2026-09-09",reason:"All reviewed Aisha source documents are written in English",status:"CONFIRMED",notes:"Translations are separate future editions."},
    {id:"d4",decision:"Resolve manuscript naming conflicts",date:"2026-09-09",reason:"The 22 September manuscript candidate has an unrelated opening title, and drafts differ on elder and camel names",status:"BLOCKED",notes:"Do not upload a manuscript to any store until the master file is identified and corrected."},
    {id:"d5",decision:"Keep private source material out of the public dashboard",date:"2026-09-09",reason:"The Command Centre is publicly hosted",status:"CONFIRMED",notes:"Store only high-level records; never include manuscript text, tokens or private Drive links."}
  ]
};

